vich_uploader:
    db_driver: orm

    metadata:
        type: annotation

    mappings:
       snowboards:
           uri_prefix: /images/snowboards
           upload_destination: '%kernel.project_dir%/public/images/snowboards'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
